/**
 * P1 "Sydney Airport -> Destination" brief, 2026-09-27: Epping pilot of the structured route
 * template.
 *
 * /sydney-airport-transfers/epping/ was seeded 2026-09-15 by seed-airport-suburb-routes-2026-09-15.ts,
 * whose copy and FAQs were one template with the suburb name substituted in - exactly what the P1
 * brief rules out. This script rewrites Epping only (the brief asks for Epping to be reviewed and
 * approved before the system is expanded) onto the new structured routeDetails fields added to
 * the Pages collection the same day:
 *
 *   direction, wheelchairAvailable, babySeatAvailable, flightMonitoring, serviceAvailability,
 *   arrivalGuide, departureGuide, earlyMorningNotes, vehicleNotes
 *
 * Once arrivalGuide is set, the frontend (transport-solutions-sydney app/[...slug]/page.tsx)
 * renders the full AirportRouteSections template - both directions, T1/T2/T3 pickup, flight
 * monitoring, vehicle capacity table, passenger/luggage guidance, wheelchair/baby seat, early
 * morning, nearby suburbs - so contentSections here only carry what's specific to Epping and
 * isn't already generated by the template (no duplicate terminal/vehicle sections).
 *
 * The other 11 route pages are untouched and keep the plain contentSections layout until they get
 * their own destination-specific copy.
 *
 * Facts are kept to stable, well-known local geography (Epping station's Metro/Northern Line
 * interchange, the station-precinct apartment towers, M2/Epping Road/Beecroft Road, Sydney
 * Airport's 11pm-6am curfew) with the same "approximately / typically / may use" qualifying
 * language as every other airport route page - no fares, no guaranteed times.
 *
 * Run with: node --env-file=.env --import tsx scripts/epping-airport-route-template-2026-09-27.ts
 * DRY_RUN=true to preview without writing.
 */
import { getPayload } from "payload";
import config from "../src/payload.config";

const SITE_KEY = "transport-solutions";
const SLUG = "sydney-airport-transfers/epping";

const routeDetails = {
  originLabel: "Sydney Airport",
  destinationSuburb: "Epping",
  destinationState: "NSW",
  destinationPostcode: "2121",
  region: "Northern Sydney",
  distanceKm: "approximately 25km by road",
  travelTime: "typically 35-50 minutes outside peak hour; allow 60+ minutes in weekday peaks",
  mainCorridor: "via the Eastern Distributor, Harbour crossing and Lane Cove Tunnel onto Epping Road, or via WestConnex and Victoria Road through Ryde",
  tollInfo: "This route may use the Eastern Distributor, Lane Cove Tunnel, M2 or WestConnex toll roads - tolls are included in your fixed, upfront fare.",
  terminals: "T1 International, T2 & T3 Domestic",
  vehicleCategories: ["Sedan", "SUV", "7 Seater", "11 Seater", "Wheelchair Accessible", "Baby/Child Seat"].map((label) => ({ label })),
  nearbySuburbs: ["Eastwood", "North Epping", "Carlingford", "Marsfield"].map((name) => ({ name })),
  direction: "both",
  wheelchairAvailable: true,
  babySeatAvailable: true,
  flightMonitoring: true,
  serviceAvailability: "24/7, including pre-dawn departures and late-night arrivals",
  arrivalGuide:
    "Landing in Sydney and heading home to Epping means a cross-city run of roughly 25km - through the Eastern Distributor and across the Harbour, or west via WestConnex and Victoria Road, whichever is moving better at the time. Much of Epping's recent growth is high-rise apartments around the station on Beecroft Road, Langston Place and Oxford Street, where kerbside stopping is tight: give us your building name and preferred entrance or loading zone and your driver will drop you and your bags as close to the lift lobby as the street allows.",
  departureGuide:
    "For flights out of Sydney, your driver collects you from your Epping address and heads for T1 or T2/T3 by the fastest available route. Weekday mornings are the pinch point: Epping Road, Beecroft Road and the approaches to the Epping station interchange typically build from around 7am, so we plan your pickup time around both your flight and local traffic rather than a fixed rule of thumb.",
  earlyMorningNotes:
    "Sydney Airport has an 11pm-6am curfew, so the first departures of the day leave from around 6am - which for Epping means a pickup before 5am. Pre-dawn roads are quiet, and the drive is usually at the shorter end of the range, but check-in and security still apply: most airlines advise arriving at least an hour before domestic flights and two to three hours before international ones. For a 6am domestic departure, a pickup around 4:15-4:30am is typical. Early pickups are booked the same way as any other - just give us your flight number and departure time.",
  vehicleNotes:
    "Collecting visiting relatives, or heading overseas as a family? International-flight luggage adds up fast, and a sedan fills before the passengers do. A 7 or 11 seater keeps everyone in one vehicle instead of two cars - one pickup at your Epping door, one fixed fare, everyone arrives together.",
};

const contentSections = [
  {
    heading: "Maxi Taxi vs Train Between Epping and Sydney Airport",
    paragraphs: [
      {
        text: "Epping station is a major interchange - the Sydney Metro and the T9 Northern Line both stop here - but neither runs to the airport. Getting from Epping to T1 or T2/T3 by train means at least one change, usually at Central, plus the airport station access fee on top of your fare. That works for a solo traveller with a backpack. For a family with suitcases, a pram or car seats, it means lifts, platforms and transfers at both ends.",
      },
      {
        text: "A pre-booked transfer goes door to door from your Epping address to the terminal kerb, with a fixed fare agreed upfront. For groups of four or more, one maxi taxi is often simpler than several train tickets plus the access fee.",
      },
    ],
    bulletList: [],
  },
  {
    heading: "Epping Pickup Tips",
    paragraphs: [],
    bulletList: [
      { text: "Apartment near the station? Tell us your building name, street entrance and whether there's a loading bay or visitor drop-off" },
      { text: "Pre-dawn pickup from a house in North Epping or Epping? Make sure your house number is visible from the street" },
      { text: "Travelling to or from Macquarie University or Macquarie Park via Marsfield? Give us the exact building or gate" },
      { text: "Leaving on a school-day morning? Allow extra time for traffic around Epping's schools and the town centre" },
    ],
  },
];

const faq = [
  {
    question: "How far is Epping from Sydney Airport, and how long does the drive take?",
    answer: "Epping is approximately 25km by road from Sydney Airport. The drive typically takes 35-50 minutes outside peak hour, and 60 minutes or more in weekday peaks, depending on whether your driver takes the Eastern Distributor and Lane Cove Tunnel or WestConnex and Victoria Road.",
  },
  {
    question: "How much is a taxi from Sydney Airport to Epping?",
    answer: "Your fare is fixed and quoted before you travel. It depends on the vehicle (sedan, SUV, 7 seater or 11 seater), the terminal, your exact Epping address, the time of travel and any tolls on the route, which are included. Request a quote online or call us for an exact price.",
  },
  {
    question: "What time should I leave Epping for an early-morning flight?",
    answer: "For a 6am domestic departure, a pickup around 4:15-4:30am is typical. Pre-dawn roads are quiet, but most airlines advise arriving at least an hour before domestic flights and two to three hours before international flights. Sydney Airport's curfew means the first flights leave from about 6am.",
  },
  {
    question: "Is a maxi taxi better than the train from Sydney Airport to Epping?",
    answer: "For a solo traveller with light luggage, the train works. For families and groups, a maxi taxi is usually easier: there's no direct train between Epping and the airport, so you change at least once (usually at Central) and pay the airport station access fee. A maxi taxi goes door to door at a fixed fare.",
  },
  {
    question: "Can you pick up from an Epping apartment building near the station?",
    answer: "Yes. Many of our Epping pickups are from the apartment towers around Beecroft Road, Langston Place and Oxford Street. Include your building name, street entrance and any loading bay or visitor drop-off when booking so your driver can meet you at the right door.",
  },
  {
    question: "Which vehicle should I book from Sydney Airport to Epping for 7 passengers?",
    answer: "For seven passengers with airport luggage, an 11 seater is usually the better choice. A 7 seater at full passenger capacity has little room left for suitcases. Tell us your passenger and bag numbers when booking so we can confirm.",
  },
  {
    question: "Do you cover North Epping, Eastwood, Carlingford and Marsfield?",
    answer: "Yes. The same Sydney Airport transfers, vehicles and fixed fares are available from North Epping, Eastwood, Carlingford and Marsfield, including pickups near Macquarie University. Just give us your exact address when booking.",
  },
  {
    question: "What happens if my flight into Sydney is delayed?",
    answer: "We monitor your flight, so your pickup time moves with your actual landing time. You don't need to call us if the flight is early or late. For international arrivals into T1, we also allow time for baggage and customs.",
  },
  {
    question: "Where do I meet my driver at Sydney Airport?",
    answer: "At T1 International, meet your driver at the designated Rideshare Pickup Area. At T2 and T3 Domestic, it's the designated Priority Pickup Area. Your driver's details are sent before you land. There's no name-board service inside the terminal.",
  },
  {
    question: "Can I book a wheelchair-accessible taxi or baby seat for Sydney Airport to Epping?",
    answer: "Yes. Wheelchair-accessible vehicles, baby capsules, child seats and boosters are all available on request for Epping transfers in both directions. Tell us your mobility needs, or each child's age, when you book.",
  },
  {
    question: "Are tolls included in the Epping airport transfer fare?",
    answer: "Yes. The route may use the Eastern Distributor, Lane Cove Tunnel, M2 or WestConnex, and any tolls are included in your fixed, upfront fare.",
  },
];

const relatedLinks = [
  { icon: "✈️", title: "Sydney Airport Transfers", description: "All Sydney Airport transfer options, terminals and vehicles.", href: "/sydney-airport-transfers/" },
  { icon: "🛫", title: "Taxi to Sydney Airport", description: "Pre-book your departure pickup from anywhere in Sydney.", href: "/taxi-to-sydney-airport/" },
  { icon: "🛬", title: "Taxi from Sydney Airport", description: "Arrival pickups from T1 International and T2/T3 Domestic.", href: "/taxi-from-sydney-airport/" },
  { icon: "💬", title: "Get an Airport Transfer Quote", description: "A fixed fare for your trip before you book.", href: "/sydney-airport-transfer-quote/" },
  { icon: "🚐", title: "11 Seater Maxi Taxi", description: "For large families and groups with luggage.", href: "/11-seater-taxi-sydney/" },
  { icon: "♿", title: "Sydney Airport Wheelchair Taxi", description: "Wheelchair-accessible airport transfers.", href: "/sydney-airport-wheelchair-taxi/" },
  { icon: "👶", title: "Sydney Airport Baby Seat Taxi", description: "Capsules, child seats and boosters fitted before pickup.", href: "/sydney-airport-baby-seat-taxi/" },
  { icon: "📍", title: "Sydney Airport to Ryde", description: "The neighbouring route to Ryde and West Ryde.", href: "/sydney-airport-transfers/ryde/" },
];

const pageData = {
  metaTitle: "Sydney Airport to Epping Maxi Taxi | 7 & 11 Seater",
  metaDescription:
    "Sydney Airport to Epping and Epping to airport transfers. Sedan, SUV, 7 & 11 seater, T1/T2/T3 pickup, flight monitoring, baby seats and wheelchair access.",
  h1: "Sydney Airport to Epping Maxi Taxi",
  heroDescription:
    "Pre-booked transfers between Sydney Airport and Epping, in both directions: pickup at T1 International or T2/T3 Domestic, drop-off at your Epping home or apartment, or collection from Epping before an early flight. Choose a sedan, SUV, 7 seater or 11 seater, with baby seats and wheelchair-accessible vehicles on request.",
  routeDetails,
  contentSections,
  faq,
  relatedLinks,
};

async function run() {
  const payload = await getPayload({ config });
  const siteResult = await payload.find({ collection: "sites", where: { key: { equals: SITE_KEY } }, limit: 1 });
  const site = siteResult.docs[0];
  if (!site) throw new Error(`Site with key "${SITE_KEY}" not found.`);

  const res = await payload.find({ collection: "pages", where: { and: [{ site: { equals: site.id } }, { slug: { equals: SLUG } }] }, limit: 1, depth: 0 });
  const doc = res.docs[0];
  if (!doc) throw new Error(`Page not found: ${SLUG}`);

  if (process.env.DRY_RUN === "true") {
    console.log(`  [${SLUG}] DRY RUN - would update (${faq.length} FAQs, ${contentSections.length} sections, ${relatedLinks.length} related links).`);
    console.log(`  metaDescription length: ${pageData.metaDescription.length}`);
    process.exit(0);
  }

  // Same stale-local-payload-types caveat as add-route-overview-fields-2026-09-17.ts.
  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  await payload.update({ collection: "pages", id: doc.id, data: pageData as any });
  console.log(`  [${SLUG}] updated (id ${doc.id}).`);
  process.exit(0);
}

run().catch((err) => {
  console.error(err);
  process.exit(1);
});
